config/routes.rb
Rails.application.routes.draw do
  root "cards#index"
  resources :cards do
    resources :decks
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  include Visible

  has_many :decks, dependent: :destroy

  validates :name, presence: true
  validates :set, presence: true, length: { maximum: 3 }
  validates :cardnum, presence: true
  validates :quantity, presence: true
  validates :image, presence: true
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = [ "public", "private", "archived"]

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: "public").count
    end
  end

  def archived?
    status == "archived"
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  include Visible

  belongs_to :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  http_basic_authenticate_with name: "pmk", password: "secret", except: [:index, :show]

  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to @card
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])

    if @card.update(card_params)
      redirect_to @card
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    redirect_to root_path, status: :see_other
  end
  private
    def card_params
      params.require(:card).permit(:name, :set, :cardnum, :quantity, :image, :status)
    end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  http_basic_authenticate_with name: "pmk", password: "secret", only: :destroy
  def create
    @card = Card.find(params[:card_id])
    @deck = @card.decks.create(deck_params)
    redirect_to card_path(@card)
  end

  def destroy
    @card = Card.find(params[:card_id])
    @deck = @card.decks.find(params[:id])
    @deck.destroy
    redirect_to card_path(@card), status: :see_other
  end

  private
    def deck_params
      params.require(:deck).permit(:name, :power_level, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/cards/_form.html.erb
<%= form_with model: card do |form| %>
    <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
        <% card.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :set %><br>
        <%= form.text_field :set %>
        <% card.errors.full_messages_for(:set).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :cardnum %><br>
        <%= form.number_field :cardnum %>
        <% card.errors.full_messages_for(:cardnum).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :quantity %><br>
        <%= form.number_field :quantity %>
        <% card.errors.full_messages_for(:quantity).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :image %><br>
        <%= form.text_field :image %>
        <% card.errors.full_messages_for(:image).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :status %>
        <%= form.select :status, Visible::VALID_STATUSES, selected: card.status || "public" %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Edit Card</h1>

<%= render "form", card: @card %>

app/views/cards/index.html.erb
<h1>Cards</h1>

Our collection has <%= Card.public_count %> cards and counting!

<ul>
    <% @cards.each do |card| %>
        <% unless card.archived? %>
            <li>
                <%= link_to card.name, card %>
            </li>
        <% end %>
    <% end %>
</ul>

<%= link_to "New Card", new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render "form", card: @card %>

app/views/cards/show.html.erb
<h1><%= @card.name %></h1>

<p><%= @card.set %>(<%= @card.cardnum %>) </p>
<p>Owned: <%= @card.quantity %></p>
<p>Status: <%= @card.status %></p>
<p><img src="<%=@card.image%>"></p>

<ul>
    <li><%= link_to "Edit", edit_card_path(@card) %></li>
    <li><%= link_to "Destroy", card_path(@card), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
    } %></li>
</ul>

<h2>Current Decks:</h2>
<%= render @card.decks %>

<h2>Add to deck:</h2>
<%= render "decks/form", card: @card %>

app/views/decks/_deck.html.erb
<% unless deck.archived? %>
    <p>
        <strong>Deck:</strong>
        <%= deck.name %>
        <strong>Power Level:</strong>
        <%= deck.power_level %>
    </p>

    <p>
        <%= link_to "Destroy Deck", [ deck.card, deck ], data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
        } %>
    </p>
<% end %>

app/views/decks/_form.html.erb
<%= form_with model: [card, card.decks.build ] do |form| %>
    <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
    </p>

    <p>
        <%= form.label :power_level %><br>
        <%= form.number_field :power_level %>
    </p>
    
    <div>
        <%= form.label :status %><br>
        <%= form.select :status, Visible::VALID_STATUSES, selected: "public" %>
    </div>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mtg" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>